---
# tasks file for ansible-commom
- include_tasks: certificates.yml
  tags: certificates

- include_tasks: ssh-keys.yml
  tags: ssh-keys

- include_tasks: i386-support.yml
  tags: i386-support

- include_tasks: locales.yml
  tags: locales

- include_tasks: unattended-upgrades.yml
  tags: unattended-upgrades

- include_tasks: sysctl.yml
  tags: sysctl

- include_tasks: ulimit.yml
  tags: ulimit

- include_tasks: esync.yml
  tags: esync

- include_tasks: iptables.yml
  tags: iptables

# - include_tasks: ntp.yml
#   tags: ntp

- include_tasks: users.yml
  tags: users

- include_tasks: sshd.yml
  tags: sshd

# - include_tasks: fail2ban.yml
#   tags: fail2ban
